# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

array_width = 167
attr_fn_like_width = 167
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
chain_width = 167
color = "Auto"
combine_control_expr = true
comment_width = 167
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
disable_all_formatting = false
doc_comment_code_block_width = 167
edition = "2024"
empty_item_single_line = false
enum_discrim_align_threshold = 133
error_on_line_overflow = false
error_on_unformatted = false
fn_call_width = 167
fn_params_layout = "Compressed"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = false
format_macro_bodies = true
format_macro_matchers = false
format_strings = true
generated_marker_line_search_limit = 5
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Preserve"
ignore = []
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 167
match_arm_blocks = false
# match_arm_indent = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = false
max_width = 167
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.8.0"
short_array_element_width_threshold = 133
show_parse_errors = true
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
skip_children = false
skip_macro_invocations = []
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 133
struct_lit_single_line = true
struct_lit_width = 133
struct_variant_width = 133
style_edition = "2024"
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = false
where_single_line = true
wrap_comments = true
